### ISSUE TITLE
libraryDependency on Readme.md unresolvable

### ISSUE THREAD

**Issue by bertzzie** [chenkelmann/actuarius#4]
Hi,

I'm thinking on using actuarius as my markdown parser for my blog. Reading on the readme.md, it says that the `libraryDependency` is:

```
libraryDependencies += "eu.henkelmann.actuarius" % "actuarius" % "0.2.4"
```

but I found this unresolvable. I'm using sbt 0.12 on play framework if that mattered.

What works for me is:

```
libraryDependencies += "eu.henkelmann" % "actuarius_2.9.2" % "0.2.4"
```

that I found out via [Maven Central Repository Search](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22actuarius_2.9.2%22)

Maybe the readme.md is not updated? I'm not sure if I should submit a pull request on this, but  I'll make one after submitting this report. If there's anything wrong, please tell me. Thank you very much.

Regards,

**Comment by chenkelmann** [comment]
Thank you for fixing that! Initially i applied for the group id "eu.henkelmann.actuarius" but I got "eu.henkelmann" instead (which is much better, as I do not need to reapply for each projekt I want to publish). I forgot to check the README after changing the project config. Hope actuarius works for you!

**Comment by bertzzie** [comment]
It works awesome for me! Keep up the good work! :)
