### ISSUE TITLE
Inline html with ticks instead of quotes are not recognized

### ISSUE THREAD

**Issue by aquamatthias** [chenkelmann/actuarius#8]
Hi,

I played around with your library - which is really a nice one.
One error is popped up:
If a user writes inline html tags with single quotes, the tag is not parsed as such and will be generated as text.

E.g.:

```
Fix tag: <span attr='ticks'>like this</span>" will be transformed to

<p>Fix tag: &lt;span attr=&apos;ticks&apos;&gt;like this</span></p>
```

Works: 

```
<span attr="ticks">like this</span>" 
```

will be transformed correctly.

Regards,
Matthias

**Comment by chenkelmann** [comment]
Hi Matthias, 

Thank you for the bug report!
That seems to be a bug in the inline html parser. I will look into it.

Regards, 

Christoph

**Comment by chenkelmann** [comment]
Fixed with version 0.2.6-SNAPSHOT. I already published the SNAPSHOT to maven central. I will test the new version with my two blogs where I use Actuarius to get some additional tests. If those tests are successful, I will change the version to 0.2.6.

**Comment by aquamatthias** [comment]
Hi Christoph,

tested with the snapshot - both issues are fixed and working.
Thanks for the fast reaction.

Best regards,
Matthias

**Comment by chenkelmann** [comment]
Thanks for helping me test!

The release of the non-snapshot version to maven central will take till the weekend I'm afraid (this weeks pretty busy)

Cheers, 

Christoph
